# Generated by Django 2.0.3 on 2018-03-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='chioce_text',
            new_name='choice_text',
        ),
    ]
